# -*- coding: utf-8 -*-

title: tonyrisk的个人博客
description: 一路走来，一路记录
email: tonylau1987@gmail.com

# 网站根路径
baseurl: "/"

# 域名
# url:              http://localhost:4000
url:              http://www.tonyrisk.info

# markdown 引擎
#markdown: kramdown
markdown: Redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "smart", "tables", "no_intra_emphasis", "autolink"]

# 代码http://pygments.org/ 或者 https://github.com/jneen/rouge
highlighter: pygments

source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
include: ['.htaccess']
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "Rakefile", "CNAME"]
keep_files: ['.git','.svn']
future: true

paginate: 5

# 预览草稿命令
# jekyll serve --draft

# 网站连接模式: http://jekyllcn.com/docs/permalinks/
permalink: /:month-:day-:year/:title.html


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# 查看可用编码 ruby -e 'puts Encoding::list.join("\n")'
encoding: UTF-8

defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"
#  -
#    scope:
#      # path: "./_projects"
#      path: ""
#      type: "posts" # previously `post` in Jekyll 2.2.(pages, drafts)
#    values:
#      layout: "post"
#      author: "Mr. Tonyrisk"
